# Generated by Django 2.2.7 on 2019-12-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
